ARCH_DEFS = /scratch/safe/SymbiFlow/symbiflow-arch-defs

install:
	- mv $(ARCH_DEFS)/xc7/primitives/dsp $(ARCH_DEFS)/xc7/primitives/dsp.`date +"%m_%d_%Y_%H_%M"`
	cp -r xc7/primitives/dsp $(ARCH_DEFS)/xc7/primitives/dsp 
	- mv  $(ARCH_DEFS)/xc7/primitives/dsp_l $(ARCH_DEFS)/xc7/primitives/dsp_l.`date +"%m_%d_%Y_%H_%M"`
	cp -r xc7/primitives/dsp_l $(ARCH_DEFS)/xc7/primitives/dsp_l 
	- mv  $(ARCH_DEFS)/xc7/primitives/dsp_r $(ARCH_DEFS)/xc7/primitives/dsp_r.`date +"%m_%d_%Y_%H_%M"`
	cp -r xc7/primitives/dsp_r $(ARCH_DEFS)/xc7/primitives/dsp_r 


