// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module update_knn1_update_knn (
        ap_clk,
        ap_rst,
        test_inst,
        train_inst,
        p_read,
        min_distances_read,
        p_read1,
        min_distances12_read,
        p_read2,
        min_distances2_read,
        p_read3,
        min_distances3_read,
        p_read4,
        min_distances4_read,
        p_read5,
        min_distances5_read,
        min_distances_offset,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [255:0] test_inst;
input  [255:0] train_inst;
input  [31:0] p_read;
input  [31:0] min_distances_read;
input  [31:0] p_read1;
input  [31:0] min_distances12_read;
input  [31:0] p_read2;
input  [31:0] min_distances2_read;
input  [31:0] p_read3;
input  [31:0] min_distances3_read;
input  [31:0] p_read4;
input  [31:0] min_distances4_read;
input  [31:0] p_read5;
input  [31:0] min_distances5_read;
input  [0:0] min_distances_offset;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
input   ap_ce;

reg[31:0] ap_return_0;
reg[31:0] ap_return_1;
reg[31:0] ap_return_2;
reg[31:0] ap_return_3;
reg[31:0] ap_return_4;
reg[31:0] ap_return_5;

reg   [31:0] p_read_1_reg_562;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] p_read_1_reg_562_pp0_iter1_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter2_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter3_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter4_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter5_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter6_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter7_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter8_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter9_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter10_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter11_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter12_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter13_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter14_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter15_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter16_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter17_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter18_reg;
reg   [31:0] p_read_1_reg_562_pp0_iter19_reg;
reg   [31:0] p_read_2_reg_568;
reg   [31:0] p_read_2_reg_568_pp0_iter1_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter2_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter3_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter4_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter5_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter6_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter7_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter8_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter9_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter10_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter11_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter12_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter13_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter14_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter15_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter16_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter17_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter18_reg;
reg   [31:0] p_read_2_reg_568_pp0_iter19_reg;
reg   [31:0] p_read_3_reg_574;
reg   [31:0] p_read_3_reg_574_pp0_iter1_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter2_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter3_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter4_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter5_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter6_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter7_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter8_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter9_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter10_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter11_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter12_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter13_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter14_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter15_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter16_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter17_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter18_reg;
reg   [31:0] p_read_3_reg_574_pp0_iter19_reg;
reg   [31:0] p_read_4_reg_580;
reg   [31:0] p_read_4_reg_580_pp0_iter1_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter2_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter3_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter4_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter5_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter6_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter7_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter8_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter9_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter10_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter11_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter12_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter13_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter14_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter15_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter16_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter17_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter18_reg;
reg   [31:0] p_read_4_reg_580_pp0_iter19_reg;
reg   [31:0] p_read_5_reg_586;
reg   [31:0] p_read_5_reg_586_pp0_iter1_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter2_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter3_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter4_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter5_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter6_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter7_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter8_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter9_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter10_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter11_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter12_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter13_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter14_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter15_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter16_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter17_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter18_reg;
reg   [31:0] p_read_5_reg_586_pp0_iter19_reg;
reg   [31:0] p_read_6_reg_592;
reg   [31:0] p_read_6_reg_592_pp0_iter1_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter2_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter3_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter4_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter5_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter6_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter7_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter8_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter9_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter10_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter11_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter12_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter13_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter14_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter15_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter16_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter17_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter18_reg;
reg   [31:0] p_read_6_reg_592_pp0_iter19_reg;
wire   [255:0] ret_fu_215_p2;
reg   [255:0] ret_reg_598;
wire   [2:0] select_ln35_3_fu_221_p3;
reg   [2:0] select_ln35_3_reg_603;
reg   [2:0] select_ln35_3_reg_603_pp0_iter1_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter2_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter3_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter4_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter5_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter6_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter7_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter8_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter9_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter10_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter11_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter12_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter13_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter14_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter15_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter16_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter17_reg;
reg   [2:0] select_ln35_3_reg_603_pp0_iter18_reg;
wire   [31:0] tmp_fu_229_p8;
reg   [31:0] tmp_reg_608;
wire   [30:0] trunc_ln35_fu_247_p1;
reg   [30:0] trunc_ln35_reg_613;
reg   [30:0] trunc_ln35_reg_613_pp0_iter1_reg;
wire   [31:0] tmp_s_fu_259_p8;
reg   [31:0] tmp_s_reg_618;
reg   [31:0] tmp_s_reg_618_pp0_iter1_reg;
reg   [31:0] tmp_s_reg_618_pp0_iter2_reg;
reg   [31:0] tmp_s_reg_618_pp0_iter3_reg;
wire   [31:0] tmp_1_fu_285_p8;
reg   [31:0] tmp_1_reg_624;
reg   [31:0] tmp_1_reg_624_pp0_iter1_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter2_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter3_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter4_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter5_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter6_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter7_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter8_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter9_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter10_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter11_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter12_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter13_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter14_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter15_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter16_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter17_reg;
reg   [31:0] tmp_1_reg_624_pp0_iter18_reg;
wire   [0:0] icmp_ln35_fu_303_p2;
reg   [0:0] icmp_ln35_reg_630;
wire   [30:0] select_ln35_fu_308_p3;
reg   [30:0] select_ln35_reg_635;
wire   [31:0] zext_ln35_fu_314_p1;
reg   [31:0] zext_ln35_reg_640;
wire   [0:0] icmp_ln35_1_fu_317_p2;
reg   [0:0] icmp_ln35_1_reg_645;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter4_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter5_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter6_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter7_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter8_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter9_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter10_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter11_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter12_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter13_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter14_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter15_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter16_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter17_reg;
reg   [0:0] icmp_ln35_1_reg_645_pp0_iter18_reg;
wire   [31:0] select_ln35_1_fu_322_p3;
reg   [31:0] select_ln35_1_reg_651;
reg   [31:0] select_ln35_1_reg_651_pp0_iter5_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter6_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter7_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter8_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter9_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter10_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter11_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter12_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter13_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter14_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter15_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter16_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter17_reg;
reg   [31:0] select_ln35_1_reg_651_pp0_iter18_reg;
wire   [8:0] grp_popcount_fu_210_ap_return;
reg   [8:0] dist_reg_657;
wire   [0:0] icmp_ln35_2_fu_327_p2;
reg   [0:0] icmp_ln35_2_reg_662;
wire   [31:0] zext_ln24_fu_331_p1;
reg   [31:0] zext_ln24_reg_668;
wire   [0:0] icmp_ln43_fu_339_p2;
reg   [0:0] icmp_ln43_reg_678;
reg   [0:0] icmp_ln43_reg_678_pp0_iter20_reg;
wire   [2:0] add_ln44_fu_359_p2;
reg   [2:0] add_ln44_reg_682;
wire   [31:0] select_ln44_1_fu_490_p3;
reg   [31:0] select_ln44_1_reg_692;
wire   [31:0] select_ln44_2_fu_496_p3;
reg   [31:0] select_ln44_2_reg_697;
wire   [31:0] select_ln44_3_fu_502_p3;
reg   [31:0] select_ln44_3_reg_702;
wire   [31:0] select_ln44_4_fu_508_p3;
reg   [31:0] select_ln44_4_reg_707;
wire   [31:0] select_ln44_5_fu_514_p3;
reg   [31:0] select_ln44_5_reg_712;
wire   [31:0] select_ln44_6_fu_520_p3;
reg   [31:0] select_ln44_6_reg_717;
reg    grp_popcount_fu_210_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call16;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call16;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call16;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call16;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call16;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call16;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call16;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call16;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call16;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call16;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call16;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call16;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call16;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call16;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call16;
wire    ap_block_state16_pp0_stage0_iter15_ignore_call16;
wire    ap_block_state17_pp0_stage0_iter16_ignore_call16;
wire    ap_block_state18_pp0_stage0_iter17_ignore_call16;
wire    ap_block_state19_pp0_stage0_iter18_ignore_call16;
wire    ap_block_state20_pp0_stage0_iter19_ignore_call16;
wire    ap_block_state21_pp0_stage0_iter20_ignore_call16;
wire    ap_block_state22_pp0_stage0_iter21_ignore_call16;
wire    ap_block_pp0_stage0_11001_ignoreCallOp46;
reg   [31:0] ap_phi_mux_phi_ln46_phi_fu_159_p4;
reg   [31:0] ap_phi_reg_pp0_iter21_phi_ln46_reg_156;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter1_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter2_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter3_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter4_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter5_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter6_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter7_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter8_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter9_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter10_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter11_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter12_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter13_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter14_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter15_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter16_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter17_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter18_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter19_phi_ln46_reg_156;
reg   [31:0] ap_phi_reg_pp0_iter20_phi_ln46_reg_156;
reg   [31:0] ap_phi_mux_phi_ln46_1_phi_fu_168_p4;
reg   [31:0] ap_phi_reg_pp0_iter21_phi_ln46_1_reg_165;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter1_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter2_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter3_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter4_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter5_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter6_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter7_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter8_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter9_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter10_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter11_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter12_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter13_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter14_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter15_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter16_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter17_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter18_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter19_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_reg_pp0_iter20_phi_ln46_1_reg_165;
reg   [31:0] ap_phi_mux_phi_ln46_2_phi_fu_177_p4;
reg   [31:0] ap_phi_reg_pp0_iter21_phi_ln46_2_reg_174;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter1_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter2_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter3_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter4_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter5_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter6_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter7_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter8_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter9_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter10_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter11_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter12_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter13_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter14_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter15_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter16_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter17_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter18_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter19_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_reg_pp0_iter20_phi_ln46_2_reg_174;
reg   [31:0] ap_phi_mux_phi_ln46_3_phi_fu_186_p4;
reg   [31:0] ap_phi_reg_pp0_iter21_phi_ln46_3_reg_183;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter1_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter2_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter3_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter4_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter5_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter6_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter7_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter8_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter9_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter10_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter11_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter12_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter13_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter14_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter15_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter16_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter17_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter18_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter19_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_reg_pp0_iter20_phi_ln46_3_reg_183;
reg   [31:0] ap_phi_mux_phi_ln46_4_phi_fu_195_p4;
reg   [31:0] ap_phi_reg_pp0_iter21_phi_ln46_4_reg_192;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter1_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter2_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter3_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter4_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter5_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter6_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter7_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter8_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter9_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter10_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter11_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter12_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter13_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter14_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter15_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter16_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter17_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter18_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter19_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_reg_pp0_iter20_phi_ln46_4_reg_192;
reg   [31:0] ap_phi_mux_phi_ln46_5_phi_fu_204_p4;
reg   [31:0] ap_phi_reg_pp0_iter21_phi_ln46_5_reg_201;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter1_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter2_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter3_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter4_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter5_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter6_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter7_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter8_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter9_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter10_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter11_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter12_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter13_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter14_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter15_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter16_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter17_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter18_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter19_phi_ln46_5_reg_201;
reg   [31:0] ap_phi_reg_pp0_iter20_phi_ln46_5_reg_201;
wire    ap_block_pp0_stage0;
wire   [2:0] tmp_fu_229_p7;
wire   [2:0] tmp_s_fu_259_p7;
wire   [2:0] tmp_1_fu_285_p7;
wire   [31:0] select_ln35_2_fu_334_p3;
wire   [1:0] zext_ln44_fu_345_p1;
wire   [1:0] select_ln44_fu_348_p3;
wire   [2:0] zext_ln44_1_fu_355_p1;
wire   [0:0] write_flag_fu_364_p10;
wire   [0:0] write_flag4_fu_427_p10;
wire   [0:0] write_flag8_fu_469_p10;
wire   [0:0] write_flag3_fu_448_p10;
wire   [0:0] write_flag2_fu_406_p10;
wire   [0:0] write_flag1_fu_385_p10;
reg    ap_ce_reg;
reg   [255:0] test_inst_int_reg;
reg   [255:0] train_inst_int_reg;
reg   [31:0] p_read_int_reg;
reg   [31:0] min_distances_read_int_reg;
reg   [31:0] p_read1_int_reg;
reg   [31:0] min_distances12_read_int_reg;
reg   [31:0] p_read2_int_reg;
reg   [31:0] min_distances2_read_int_reg;
reg   [31:0] p_read3_int_reg;
reg   [31:0] min_distances3_read_int_reg;
reg   [31:0] p_read4_int_reg;
reg   [31:0] min_distances4_read_int_reg;
reg   [31:0] p_read5_int_reg;
reg   [31:0] min_distances5_read_int_reg;
reg   [0:0] min_distances_offset_int_reg;
reg   [31:0] ap_return_0_int_reg;
reg   [31:0] ap_return_1_int_reg;
reg   [31:0] ap_return_2_int_reg;
reg   [31:0] ap_return_3_int_reg;
reg   [31:0] ap_return_4_int_reg;
reg   [31:0] ap_return_5_int_reg;

update_knn1_popcount grp_popcount_fu_210(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(ret_reg_598),
    .ap_return(grp_popcount_fu_210_ap_return),
    .ap_ce(grp_popcount_fu_210_ap_ce)
);

update_knn1_mux_63_32_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_63_32_1_0_U2(
    .din0(min_distances_read_int_reg),
    .din1(min_distances12_read_int_reg),
    .din2(min_distances2_read_int_reg),
    .din3(min_distances3_read_int_reg),
    .din4(min_distances4_read_int_reg),
    .din5(min_distances5_read_int_reg),
    .din6(tmp_fu_229_p7),
    .dout(tmp_fu_229_p8)
);

update_knn1_mux_63_32_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_63_32_1_0_U3(
    .din0(min_distances_read_int_reg),
    .din1(min_distances12_read_int_reg),
    .din2(min_distances2_read_int_reg),
    .din3(min_distances3_read_int_reg),
    .din4(min_distances4_read_int_reg),
    .din5(min_distances5_read_int_reg),
    .din6(tmp_s_fu_259_p7),
    .dout(tmp_s_fu_259_p8)
);

update_knn1_mux_63_32_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_63_32_1_0_U4(
    .din0(min_distances_read_int_reg),
    .din1(min_distances12_read_int_reg),
    .din2(min_distances2_read_int_reg),
    .din3(min_distances3_read_int_reg),
    .din4(min_distances4_read_int_reg),
    .din5(min_distances5_read_int_reg),
    .din6(tmp_1_fu_285_p7),
    .dout(tmp_1_fu_285_p8)
);

update_knn1_mux_83_1_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
mux_83_1_1_0_U5(
    .din0(1'd1),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd0),
    .din6(1'd0),
    .din7(1'd0),
    .din8(add_ln44_reg_682),
    .dout(write_flag_fu_364_p10)
);

update_knn1_mux_83_1_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
mux_83_1_1_0_U6(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd1),
    .din8(add_ln44_reg_682),
    .dout(write_flag1_fu_385_p10)
);

update_knn1_mux_83_1_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
mux_83_1_1_0_U7(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd0),
    .din6(1'd0),
    .din7(1'd0),
    .din8(add_ln44_reg_682),
    .dout(write_flag2_fu_406_p10)
);

update_knn1_mux_83_1_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
mux_83_1_1_0_U8(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd0),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd0),
    .din6(1'd0),
    .din7(1'd0),
    .din8(add_ln44_reg_682),
    .dout(write_flag4_fu_427_p10)
);

update_knn1_mux_83_1_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
mux_83_1_1_0_U9(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd0),
    .din5(1'd0),
    .din6(1'd0),
    .din7(1'd0),
    .din8(add_ln44_reg_682),
    .dout(write_flag3_fu_448_p10)
);

update_knn1_mux_83_1_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
mux_83_1_1_0_U10(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd0),
    .din6(1'd0),
    .din7(1'd0),
    .din8(add_ln44_reg_682),
    .dout(write_flag8_fu_469_p10)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((icmp_ln43_reg_678 == 1'd0)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_1_reg_165 <= p_read_3_reg_574_pp0_iter19_reg;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter20_phi_ln46_1_reg_165;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((icmp_ln43_reg_678 == 1'd0)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_2_reg_174 <= p_read_5_reg_586_pp0_iter19_reg;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter20_phi_ln46_2_reg_174;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((icmp_ln43_reg_678 == 1'd0)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_3_reg_183 <= p_read_2_reg_568_pp0_iter19_reg;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter20_phi_ln46_3_reg_183;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((icmp_ln43_reg_678 == 1'd0)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_4_reg_192 <= p_read_1_reg_562_pp0_iter19_reg;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter20_phi_ln46_4_reg_192;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((icmp_ln43_reg_678 == 1'd0)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_5_reg_201 <= p_read_6_reg_592_pp0_iter19_reg;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter20_phi_ln46_5_reg_201;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((icmp_ln43_reg_678 == 1'd0)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_reg_156 <= p_read_4_reg_580_pp0_iter19_reg;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter21_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter20_phi_ln46_reg_156;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_fu_339_p2 == 1'd1) & (1'b1 == ap_ce_reg))) begin
        add_ln44_reg_682 <= add_ln44_fu_359_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        ap_phi_reg_pp0_iter10_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter9_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter10_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter9_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter10_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter9_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter10_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter9_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter10_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter9_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter10_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter9_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter11_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter10_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter11_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter10_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter11_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter10_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter11_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter10_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter11_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter10_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter11_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter10_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter12_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter11_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter12_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter11_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter12_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter11_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter12_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter11_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter12_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter11_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter12_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter11_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter13_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter12_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter13_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter12_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter13_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter12_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter13_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter12_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter13_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter12_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter13_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter12_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter14_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter13_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter14_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter13_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter14_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter13_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter14_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter13_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter14_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter13_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter14_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter13_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter15_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter14_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter15_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter14_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter15_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter14_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter15_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter14_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter15_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter14_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter15_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter14_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter16_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter15_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter16_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter15_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter16_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter15_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter16_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter15_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter16_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter15_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter16_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter15_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter17_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter16_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter17_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter16_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter17_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter16_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter17_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter16_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter17_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter16_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter17_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter16_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter18_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter17_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter18_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter17_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter18_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter17_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter18_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter17_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter18_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter17_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter18_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter17_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter19_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter18_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter19_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter18_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter19_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter18_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter19_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter18_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter19_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter18_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter19_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter18_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter1_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter0_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter1_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter0_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter1_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter0_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter1_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter0_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter1_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter0_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter1_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter0_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter20_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter19_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter20_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter19_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter20_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter19_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter20_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter19_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter20_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter19_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter20_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter19_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter2_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter1_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter2_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter1_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter2_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter1_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter2_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter1_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter2_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter1_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter2_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter1_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter3_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter2_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter3_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter2_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter3_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter2_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter3_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter2_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter3_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter2_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter3_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter2_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter4_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter3_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter4_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter3_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter4_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter3_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter4_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter3_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter4_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter3_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter4_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter3_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter5_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter4_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter5_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter4_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter5_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter4_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter5_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter4_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter5_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter4_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter5_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter4_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter6_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter5_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter6_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter5_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter6_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter5_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter6_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter5_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter6_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter5_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter6_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter5_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter7_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter6_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter7_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter6_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter7_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter6_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter7_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter6_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter7_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter6_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter7_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter6_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter8_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter7_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter8_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter7_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter8_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter7_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter8_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter7_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter8_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter7_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter8_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter7_phi_ln46_reg_156;
        ap_phi_reg_pp0_iter9_phi_ln46_1_reg_165 <= ap_phi_reg_pp0_iter8_phi_ln46_1_reg_165;
        ap_phi_reg_pp0_iter9_phi_ln46_2_reg_174 <= ap_phi_reg_pp0_iter8_phi_ln46_2_reg_174;
        ap_phi_reg_pp0_iter9_phi_ln46_3_reg_183 <= ap_phi_reg_pp0_iter8_phi_ln46_3_reg_183;
        ap_phi_reg_pp0_iter9_phi_ln46_4_reg_192 <= ap_phi_reg_pp0_iter8_phi_ln46_4_reg_192;
        ap_phi_reg_pp0_iter9_phi_ln46_5_reg_201 <= ap_phi_reg_pp0_iter8_phi_ln46_5_reg_201;
        ap_phi_reg_pp0_iter9_phi_ln46_reg_156 <= ap_phi_reg_pp0_iter8_phi_ln46_reg_156;
        dist_reg_657 <= grp_popcount_fu_210_ap_return;
        icmp_ln35_1_reg_645 <= icmp_ln35_1_fu_317_p2;
        icmp_ln35_1_reg_645_pp0_iter10_reg <= icmp_ln35_1_reg_645_pp0_iter9_reg;
        icmp_ln35_1_reg_645_pp0_iter11_reg <= icmp_ln35_1_reg_645_pp0_iter10_reg;
        icmp_ln35_1_reg_645_pp0_iter12_reg <= icmp_ln35_1_reg_645_pp0_iter11_reg;
        icmp_ln35_1_reg_645_pp0_iter13_reg <= icmp_ln35_1_reg_645_pp0_iter12_reg;
        icmp_ln35_1_reg_645_pp0_iter14_reg <= icmp_ln35_1_reg_645_pp0_iter13_reg;
        icmp_ln35_1_reg_645_pp0_iter15_reg <= icmp_ln35_1_reg_645_pp0_iter14_reg;
        icmp_ln35_1_reg_645_pp0_iter16_reg <= icmp_ln35_1_reg_645_pp0_iter15_reg;
        icmp_ln35_1_reg_645_pp0_iter17_reg <= icmp_ln35_1_reg_645_pp0_iter16_reg;
        icmp_ln35_1_reg_645_pp0_iter18_reg <= icmp_ln35_1_reg_645_pp0_iter17_reg;
        icmp_ln35_1_reg_645_pp0_iter4_reg <= icmp_ln35_1_reg_645;
        icmp_ln35_1_reg_645_pp0_iter5_reg <= icmp_ln35_1_reg_645_pp0_iter4_reg;
        icmp_ln35_1_reg_645_pp0_iter6_reg <= icmp_ln35_1_reg_645_pp0_iter5_reg;
        icmp_ln35_1_reg_645_pp0_iter7_reg <= icmp_ln35_1_reg_645_pp0_iter6_reg;
        icmp_ln35_1_reg_645_pp0_iter8_reg <= icmp_ln35_1_reg_645_pp0_iter7_reg;
        icmp_ln35_1_reg_645_pp0_iter9_reg <= icmp_ln35_1_reg_645_pp0_iter8_reg;
        icmp_ln35_2_reg_662 <= icmp_ln35_2_fu_327_p2;
        icmp_ln35_reg_630 <= icmp_ln35_fu_303_p2;
        icmp_ln43_reg_678 <= icmp_ln43_fu_339_p2;
        icmp_ln43_reg_678_pp0_iter20_reg <= icmp_ln43_reg_678;
        p_read_1_reg_562 <= p_read5_int_reg;
        p_read_1_reg_562_pp0_iter10_reg <= p_read_1_reg_562_pp0_iter9_reg;
        p_read_1_reg_562_pp0_iter11_reg <= p_read_1_reg_562_pp0_iter10_reg;
        p_read_1_reg_562_pp0_iter12_reg <= p_read_1_reg_562_pp0_iter11_reg;
        p_read_1_reg_562_pp0_iter13_reg <= p_read_1_reg_562_pp0_iter12_reg;
        p_read_1_reg_562_pp0_iter14_reg <= p_read_1_reg_562_pp0_iter13_reg;
        p_read_1_reg_562_pp0_iter15_reg <= p_read_1_reg_562_pp0_iter14_reg;
        p_read_1_reg_562_pp0_iter16_reg <= p_read_1_reg_562_pp0_iter15_reg;
        p_read_1_reg_562_pp0_iter17_reg <= p_read_1_reg_562_pp0_iter16_reg;
        p_read_1_reg_562_pp0_iter18_reg <= p_read_1_reg_562_pp0_iter17_reg;
        p_read_1_reg_562_pp0_iter19_reg <= p_read_1_reg_562_pp0_iter18_reg;
        p_read_1_reg_562_pp0_iter1_reg <= p_read_1_reg_562;
        p_read_1_reg_562_pp0_iter2_reg <= p_read_1_reg_562_pp0_iter1_reg;
        p_read_1_reg_562_pp0_iter3_reg <= p_read_1_reg_562_pp0_iter2_reg;
        p_read_1_reg_562_pp0_iter4_reg <= p_read_1_reg_562_pp0_iter3_reg;
        p_read_1_reg_562_pp0_iter5_reg <= p_read_1_reg_562_pp0_iter4_reg;
        p_read_1_reg_562_pp0_iter6_reg <= p_read_1_reg_562_pp0_iter5_reg;
        p_read_1_reg_562_pp0_iter7_reg <= p_read_1_reg_562_pp0_iter6_reg;
        p_read_1_reg_562_pp0_iter8_reg <= p_read_1_reg_562_pp0_iter7_reg;
        p_read_1_reg_562_pp0_iter9_reg <= p_read_1_reg_562_pp0_iter8_reg;
        p_read_2_reg_568 <= p_read4_int_reg;
        p_read_2_reg_568_pp0_iter10_reg <= p_read_2_reg_568_pp0_iter9_reg;
        p_read_2_reg_568_pp0_iter11_reg <= p_read_2_reg_568_pp0_iter10_reg;
        p_read_2_reg_568_pp0_iter12_reg <= p_read_2_reg_568_pp0_iter11_reg;
        p_read_2_reg_568_pp0_iter13_reg <= p_read_2_reg_568_pp0_iter12_reg;
        p_read_2_reg_568_pp0_iter14_reg <= p_read_2_reg_568_pp0_iter13_reg;
        p_read_2_reg_568_pp0_iter15_reg <= p_read_2_reg_568_pp0_iter14_reg;
        p_read_2_reg_568_pp0_iter16_reg <= p_read_2_reg_568_pp0_iter15_reg;
        p_read_2_reg_568_pp0_iter17_reg <= p_read_2_reg_568_pp0_iter16_reg;
        p_read_2_reg_568_pp0_iter18_reg <= p_read_2_reg_568_pp0_iter17_reg;
        p_read_2_reg_568_pp0_iter19_reg <= p_read_2_reg_568_pp0_iter18_reg;
        p_read_2_reg_568_pp0_iter1_reg <= p_read_2_reg_568;
        p_read_2_reg_568_pp0_iter2_reg <= p_read_2_reg_568_pp0_iter1_reg;
        p_read_2_reg_568_pp0_iter3_reg <= p_read_2_reg_568_pp0_iter2_reg;
        p_read_2_reg_568_pp0_iter4_reg <= p_read_2_reg_568_pp0_iter3_reg;
        p_read_2_reg_568_pp0_iter5_reg <= p_read_2_reg_568_pp0_iter4_reg;
        p_read_2_reg_568_pp0_iter6_reg <= p_read_2_reg_568_pp0_iter5_reg;
        p_read_2_reg_568_pp0_iter7_reg <= p_read_2_reg_568_pp0_iter6_reg;
        p_read_2_reg_568_pp0_iter8_reg <= p_read_2_reg_568_pp0_iter7_reg;
        p_read_2_reg_568_pp0_iter9_reg <= p_read_2_reg_568_pp0_iter8_reg;
        p_read_3_reg_574 <= p_read3_int_reg;
        p_read_3_reg_574_pp0_iter10_reg <= p_read_3_reg_574_pp0_iter9_reg;
        p_read_3_reg_574_pp0_iter11_reg <= p_read_3_reg_574_pp0_iter10_reg;
        p_read_3_reg_574_pp0_iter12_reg <= p_read_3_reg_574_pp0_iter11_reg;
        p_read_3_reg_574_pp0_iter13_reg <= p_read_3_reg_574_pp0_iter12_reg;
        p_read_3_reg_574_pp0_iter14_reg <= p_read_3_reg_574_pp0_iter13_reg;
        p_read_3_reg_574_pp0_iter15_reg <= p_read_3_reg_574_pp0_iter14_reg;
        p_read_3_reg_574_pp0_iter16_reg <= p_read_3_reg_574_pp0_iter15_reg;
        p_read_3_reg_574_pp0_iter17_reg <= p_read_3_reg_574_pp0_iter16_reg;
        p_read_3_reg_574_pp0_iter18_reg <= p_read_3_reg_574_pp0_iter17_reg;
        p_read_3_reg_574_pp0_iter19_reg <= p_read_3_reg_574_pp0_iter18_reg;
        p_read_3_reg_574_pp0_iter1_reg <= p_read_3_reg_574;
        p_read_3_reg_574_pp0_iter2_reg <= p_read_3_reg_574_pp0_iter1_reg;
        p_read_3_reg_574_pp0_iter3_reg <= p_read_3_reg_574_pp0_iter2_reg;
        p_read_3_reg_574_pp0_iter4_reg <= p_read_3_reg_574_pp0_iter3_reg;
        p_read_3_reg_574_pp0_iter5_reg <= p_read_3_reg_574_pp0_iter4_reg;
        p_read_3_reg_574_pp0_iter6_reg <= p_read_3_reg_574_pp0_iter5_reg;
        p_read_3_reg_574_pp0_iter7_reg <= p_read_3_reg_574_pp0_iter6_reg;
        p_read_3_reg_574_pp0_iter8_reg <= p_read_3_reg_574_pp0_iter7_reg;
        p_read_3_reg_574_pp0_iter9_reg <= p_read_3_reg_574_pp0_iter8_reg;
        p_read_4_reg_580 <= p_read2_int_reg;
        p_read_4_reg_580_pp0_iter10_reg <= p_read_4_reg_580_pp0_iter9_reg;
        p_read_4_reg_580_pp0_iter11_reg <= p_read_4_reg_580_pp0_iter10_reg;
        p_read_4_reg_580_pp0_iter12_reg <= p_read_4_reg_580_pp0_iter11_reg;
        p_read_4_reg_580_pp0_iter13_reg <= p_read_4_reg_580_pp0_iter12_reg;
        p_read_4_reg_580_pp0_iter14_reg <= p_read_4_reg_580_pp0_iter13_reg;
        p_read_4_reg_580_pp0_iter15_reg <= p_read_4_reg_580_pp0_iter14_reg;
        p_read_4_reg_580_pp0_iter16_reg <= p_read_4_reg_580_pp0_iter15_reg;
        p_read_4_reg_580_pp0_iter17_reg <= p_read_4_reg_580_pp0_iter16_reg;
        p_read_4_reg_580_pp0_iter18_reg <= p_read_4_reg_580_pp0_iter17_reg;
        p_read_4_reg_580_pp0_iter19_reg <= p_read_4_reg_580_pp0_iter18_reg;
        p_read_4_reg_580_pp0_iter1_reg <= p_read_4_reg_580;
        p_read_4_reg_580_pp0_iter2_reg <= p_read_4_reg_580_pp0_iter1_reg;
        p_read_4_reg_580_pp0_iter3_reg <= p_read_4_reg_580_pp0_iter2_reg;
        p_read_4_reg_580_pp0_iter4_reg <= p_read_4_reg_580_pp0_iter3_reg;
        p_read_4_reg_580_pp0_iter5_reg <= p_read_4_reg_580_pp0_iter4_reg;
        p_read_4_reg_580_pp0_iter6_reg <= p_read_4_reg_580_pp0_iter5_reg;
        p_read_4_reg_580_pp0_iter7_reg <= p_read_4_reg_580_pp0_iter6_reg;
        p_read_4_reg_580_pp0_iter8_reg <= p_read_4_reg_580_pp0_iter7_reg;
        p_read_4_reg_580_pp0_iter9_reg <= p_read_4_reg_580_pp0_iter8_reg;
        p_read_5_reg_586 <= p_read1_int_reg;
        p_read_5_reg_586_pp0_iter10_reg <= p_read_5_reg_586_pp0_iter9_reg;
        p_read_5_reg_586_pp0_iter11_reg <= p_read_5_reg_586_pp0_iter10_reg;
        p_read_5_reg_586_pp0_iter12_reg <= p_read_5_reg_586_pp0_iter11_reg;
        p_read_5_reg_586_pp0_iter13_reg <= p_read_5_reg_586_pp0_iter12_reg;
        p_read_5_reg_586_pp0_iter14_reg <= p_read_5_reg_586_pp0_iter13_reg;
        p_read_5_reg_586_pp0_iter15_reg <= p_read_5_reg_586_pp0_iter14_reg;
        p_read_5_reg_586_pp0_iter16_reg <= p_read_5_reg_586_pp0_iter15_reg;
        p_read_5_reg_586_pp0_iter17_reg <= p_read_5_reg_586_pp0_iter16_reg;
        p_read_5_reg_586_pp0_iter18_reg <= p_read_5_reg_586_pp0_iter17_reg;
        p_read_5_reg_586_pp0_iter19_reg <= p_read_5_reg_586_pp0_iter18_reg;
        p_read_5_reg_586_pp0_iter1_reg <= p_read_5_reg_586;
        p_read_5_reg_586_pp0_iter2_reg <= p_read_5_reg_586_pp0_iter1_reg;
        p_read_5_reg_586_pp0_iter3_reg <= p_read_5_reg_586_pp0_iter2_reg;
        p_read_5_reg_586_pp0_iter4_reg <= p_read_5_reg_586_pp0_iter3_reg;
        p_read_5_reg_586_pp0_iter5_reg <= p_read_5_reg_586_pp0_iter4_reg;
        p_read_5_reg_586_pp0_iter6_reg <= p_read_5_reg_586_pp0_iter5_reg;
        p_read_5_reg_586_pp0_iter7_reg <= p_read_5_reg_586_pp0_iter6_reg;
        p_read_5_reg_586_pp0_iter8_reg <= p_read_5_reg_586_pp0_iter7_reg;
        p_read_5_reg_586_pp0_iter9_reg <= p_read_5_reg_586_pp0_iter8_reg;
        p_read_6_reg_592 <= p_read_int_reg;
        p_read_6_reg_592_pp0_iter10_reg <= p_read_6_reg_592_pp0_iter9_reg;
        p_read_6_reg_592_pp0_iter11_reg <= p_read_6_reg_592_pp0_iter10_reg;
        p_read_6_reg_592_pp0_iter12_reg <= p_read_6_reg_592_pp0_iter11_reg;
        p_read_6_reg_592_pp0_iter13_reg <= p_read_6_reg_592_pp0_iter12_reg;
        p_read_6_reg_592_pp0_iter14_reg <= p_read_6_reg_592_pp0_iter13_reg;
        p_read_6_reg_592_pp0_iter15_reg <= p_read_6_reg_592_pp0_iter14_reg;
        p_read_6_reg_592_pp0_iter16_reg <= p_read_6_reg_592_pp0_iter15_reg;
        p_read_6_reg_592_pp0_iter17_reg <= p_read_6_reg_592_pp0_iter16_reg;
        p_read_6_reg_592_pp0_iter18_reg <= p_read_6_reg_592_pp0_iter17_reg;
        p_read_6_reg_592_pp0_iter19_reg <= p_read_6_reg_592_pp0_iter18_reg;
        p_read_6_reg_592_pp0_iter1_reg <= p_read_6_reg_592;
        p_read_6_reg_592_pp0_iter2_reg <= p_read_6_reg_592_pp0_iter1_reg;
        p_read_6_reg_592_pp0_iter3_reg <= p_read_6_reg_592_pp0_iter2_reg;
        p_read_6_reg_592_pp0_iter4_reg <= p_read_6_reg_592_pp0_iter3_reg;
        p_read_6_reg_592_pp0_iter5_reg <= p_read_6_reg_592_pp0_iter4_reg;
        p_read_6_reg_592_pp0_iter6_reg <= p_read_6_reg_592_pp0_iter5_reg;
        p_read_6_reg_592_pp0_iter7_reg <= p_read_6_reg_592_pp0_iter6_reg;
        p_read_6_reg_592_pp0_iter8_reg <= p_read_6_reg_592_pp0_iter7_reg;
        p_read_6_reg_592_pp0_iter9_reg <= p_read_6_reg_592_pp0_iter8_reg;
        ret_reg_598 <= ret_fu_215_p2;
        select_ln35_1_reg_651 <= select_ln35_1_fu_322_p3;
        select_ln35_1_reg_651_pp0_iter10_reg <= select_ln35_1_reg_651_pp0_iter9_reg;
        select_ln35_1_reg_651_pp0_iter11_reg <= select_ln35_1_reg_651_pp0_iter10_reg;
        select_ln35_1_reg_651_pp0_iter12_reg <= select_ln35_1_reg_651_pp0_iter11_reg;
        select_ln35_1_reg_651_pp0_iter13_reg <= select_ln35_1_reg_651_pp0_iter12_reg;
        select_ln35_1_reg_651_pp0_iter14_reg <= select_ln35_1_reg_651_pp0_iter13_reg;
        select_ln35_1_reg_651_pp0_iter15_reg <= select_ln35_1_reg_651_pp0_iter14_reg;
        select_ln35_1_reg_651_pp0_iter16_reg <= select_ln35_1_reg_651_pp0_iter15_reg;
        select_ln35_1_reg_651_pp0_iter17_reg <= select_ln35_1_reg_651_pp0_iter16_reg;
        select_ln35_1_reg_651_pp0_iter18_reg <= select_ln35_1_reg_651_pp0_iter17_reg;
        select_ln35_1_reg_651_pp0_iter5_reg <= select_ln35_1_reg_651;
        select_ln35_1_reg_651_pp0_iter6_reg <= select_ln35_1_reg_651_pp0_iter5_reg;
        select_ln35_1_reg_651_pp0_iter7_reg <= select_ln35_1_reg_651_pp0_iter6_reg;
        select_ln35_1_reg_651_pp0_iter8_reg <= select_ln35_1_reg_651_pp0_iter7_reg;
        select_ln35_1_reg_651_pp0_iter9_reg <= select_ln35_1_reg_651_pp0_iter8_reg;
        select_ln35_3_reg_603[1 : 0] <= select_ln35_3_fu_221_p3[1 : 0];
        select_ln35_3_reg_603_pp0_iter10_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter9_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter11_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter10_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter12_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter11_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter13_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter12_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter14_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter13_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter15_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter14_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter16_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter15_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter17_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter16_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter18_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter17_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter1_reg[1 : 0] <= select_ln35_3_reg_603[1 : 0];
        select_ln35_3_reg_603_pp0_iter2_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter1_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter3_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter2_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter4_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter3_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter5_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter4_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter6_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter5_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter7_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter6_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter8_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter7_reg[1 : 0];
        select_ln35_3_reg_603_pp0_iter9_reg[1 : 0] <= select_ln35_3_reg_603_pp0_iter8_reg[1 : 0];
        select_ln35_reg_635 <= select_ln35_fu_308_p3;
        tmp_1_reg_624 <= tmp_1_fu_285_p8;
        tmp_1_reg_624_pp0_iter10_reg <= tmp_1_reg_624_pp0_iter9_reg;
        tmp_1_reg_624_pp0_iter11_reg <= tmp_1_reg_624_pp0_iter10_reg;
        tmp_1_reg_624_pp0_iter12_reg <= tmp_1_reg_624_pp0_iter11_reg;
        tmp_1_reg_624_pp0_iter13_reg <= tmp_1_reg_624_pp0_iter12_reg;
        tmp_1_reg_624_pp0_iter14_reg <= tmp_1_reg_624_pp0_iter13_reg;
        tmp_1_reg_624_pp0_iter15_reg <= tmp_1_reg_624_pp0_iter14_reg;
        tmp_1_reg_624_pp0_iter16_reg <= tmp_1_reg_624_pp0_iter15_reg;
        tmp_1_reg_624_pp0_iter17_reg <= tmp_1_reg_624_pp0_iter16_reg;
        tmp_1_reg_624_pp0_iter18_reg <= tmp_1_reg_624_pp0_iter17_reg;
        tmp_1_reg_624_pp0_iter1_reg <= tmp_1_reg_624;
        tmp_1_reg_624_pp0_iter2_reg <= tmp_1_reg_624_pp0_iter1_reg;
        tmp_1_reg_624_pp0_iter3_reg <= tmp_1_reg_624_pp0_iter2_reg;
        tmp_1_reg_624_pp0_iter4_reg <= tmp_1_reg_624_pp0_iter3_reg;
        tmp_1_reg_624_pp0_iter5_reg <= tmp_1_reg_624_pp0_iter4_reg;
        tmp_1_reg_624_pp0_iter6_reg <= tmp_1_reg_624_pp0_iter5_reg;
        tmp_1_reg_624_pp0_iter7_reg <= tmp_1_reg_624_pp0_iter6_reg;
        tmp_1_reg_624_pp0_iter8_reg <= tmp_1_reg_624_pp0_iter7_reg;
        tmp_1_reg_624_pp0_iter9_reg <= tmp_1_reg_624_pp0_iter8_reg;
        tmp_reg_608 <= tmp_fu_229_p8;
        tmp_s_reg_618 <= tmp_s_fu_259_p8;
        tmp_s_reg_618_pp0_iter1_reg <= tmp_s_reg_618;
        tmp_s_reg_618_pp0_iter2_reg <= tmp_s_reg_618_pp0_iter1_reg;
        tmp_s_reg_618_pp0_iter3_reg <= tmp_s_reg_618_pp0_iter2_reg;
        trunc_ln35_reg_613 <= trunc_ln35_fu_247_p1;
        trunc_ln35_reg_613_pp0_iter1_reg <= trunc_ln35_reg_613;
        zext_ln24_reg_668[8 : 0] <= zext_ln24_fu_331_p1[8 : 0];
        zext_ln35_reg_640[30 : 0] <= zext_ln35_fu_314_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= ap_phi_mux_phi_ln46_5_phi_fu_204_p4;
        ap_return_1_int_reg <= ap_phi_mux_phi_ln46_2_phi_fu_177_p4;
        ap_return_2_int_reg <= ap_phi_mux_phi_ln46_phi_fu_159_p4;
        ap_return_3_int_reg <= ap_phi_mux_phi_ln46_1_phi_fu_168_p4;
        ap_return_4_int_reg <= ap_phi_mux_phi_ln46_3_phi_fu_186_p4;
        ap_return_5_int_reg <= ap_phi_mux_phi_ln46_4_phi_fu_195_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        min_distances12_read_int_reg <= min_distances12_read;
        min_distances2_read_int_reg <= min_distances2_read;
        min_distances3_read_int_reg <= min_distances3_read;
        min_distances4_read_int_reg <= min_distances4_read;
        min_distances5_read_int_reg <= min_distances5_read;
        min_distances_offset_int_reg <= min_distances_offset;
        min_distances_read_int_reg <= min_distances_read;
        p_read1_int_reg <= p_read1;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
        p_read4_int_reg <= p_read4;
        p_read5_int_reg <= p_read5;
        p_read_int_reg <= p_read;
        test_inst_int_reg <= test_inst;
        train_inst_int_reg <= train_inst;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_678 == 1'd1) & (1'b1 == ap_ce_reg))) begin
        select_ln44_1_reg_692 <= select_ln44_1_fu_490_p3;
        select_ln44_2_reg_697 <= select_ln44_2_fu_496_p3;
        select_ln44_3_reg_702 <= select_ln44_3_fu_502_p3;
        select_ln44_4_reg_707 <= select_ln44_4_fu_508_p3;
        select_ln44_5_reg_712 <= select_ln44_5_fu_514_p3;
        select_ln44_6_reg_717 <= select_ln44_6_fu_520_p3;
    end
end

always @ (*) begin
    if ((icmp_ln43_reg_678_pp0_iter20_reg == 1'd1)) begin
        ap_phi_mux_phi_ln46_1_phi_fu_168_p4 = select_ln44_4_reg_707;
    end else begin
        ap_phi_mux_phi_ln46_1_phi_fu_168_p4 = ap_phi_reg_pp0_iter21_phi_ln46_1_reg_165;
    end
end

always @ (*) begin
    if ((icmp_ln43_reg_678_pp0_iter20_reg == 1'd1)) begin
        ap_phi_mux_phi_ln46_2_phi_fu_177_p4 = select_ln44_2_reg_697;
    end else begin
        ap_phi_mux_phi_ln46_2_phi_fu_177_p4 = ap_phi_reg_pp0_iter21_phi_ln46_2_reg_174;
    end
end

always @ (*) begin
    if ((icmp_ln43_reg_678_pp0_iter20_reg == 1'd1)) begin
        ap_phi_mux_phi_ln46_3_phi_fu_186_p4 = select_ln44_5_reg_712;
    end else begin
        ap_phi_mux_phi_ln46_3_phi_fu_186_p4 = ap_phi_reg_pp0_iter21_phi_ln46_3_reg_183;
    end
end

always @ (*) begin
    if ((icmp_ln43_reg_678_pp0_iter20_reg == 1'd1)) begin
        ap_phi_mux_phi_ln46_4_phi_fu_195_p4 = select_ln44_6_reg_717;
    end else begin
        ap_phi_mux_phi_ln46_4_phi_fu_195_p4 = ap_phi_reg_pp0_iter21_phi_ln46_4_reg_192;
    end
end

always @ (*) begin
    if ((icmp_ln43_reg_678_pp0_iter20_reg == 1'd1)) begin
        ap_phi_mux_phi_ln46_5_phi_fu_204_p4 = select_ln44_1_reg_692;
    end else begin
        ap_phi_mux_phi_ln46_5_phi_fu_204_p4 = ap_phi_reg_pp0_iter21_phi_ln46_5_reg_201;
    end
end

always @ (*) begin
    if ((icmp_ln43_reg_678_pp0_iter20_reg == 1'd1)) begin
        ap_phi_mux_phi_ln46_phi_fu_159_p4 = select_ln44_3_reg_702;
    end else begin
        ap_phi_mux_phi_ln46_phi_fu_159_p4 = ap_phi_reg_pp0_iter21_phi_ln46_reg_156;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = ap_phi_mux_phi_ln46_5_phi_fu_204_p4;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = ap_phi_mux_phi_ln46_2_phi_fu_177_p4;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = ap_phi_mux_phi_ln46_phi_fu_159_p4;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = ap_phi_mux_phi_ln46_1_phi_fu_168_p4;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = ap_phi_mux_phi_ln46_3_phi_fu_186_p4;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = ap_phi_mux_phi_ln46_4_phi_fu_195_p4;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp46) & (1'b1 == ap_ce_reg))) begin
        grp_popcount_fu_210_ap_ce = 1'b1;
    end else begin
        grp_popcount_fu_210_ap_ce = 1'b0;
    end
end

assign add_ln44_fu_359_p2 = (zext_ln44_1_fu_355_p1 + select_ln35_3_reg_603_pp0_iter18_reg);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp46 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_phi_reg_pp0_iter0_phi_ln46_1_reg_165 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln46_2_reg_174 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln46_3_reg_183 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln46_4_reg_192 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln46_5_reg_201 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln46_reg_156 = 'bx;

assign icmp_ln35_1_fu_317_p2 = (($signed(tmp_s_reg_618_pp0_iter2_reg) > $signed(zext_ln35_fu_314_p1)) ? 1'b1 : 1'b0);

assign icmp_ln35_2_fu_327_p2 = (($signed(tmp_1_reg_624_pp0_iter17_reg) > $signed(select_ln35_1_reg_651_pp0_iter17_reg)) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_303_p2 = (($signed(tmp_reg_608) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_339_p2 = (($signed(zext_ln24_fu_331_p1) < $signed(select_ln35_2_fu_334_p3)) ? 1'b1 : 1'b0);

assign ret_fu_215_p2 = (train_inst_int_reg ^ test_inst_int_reg);

assign select_ln35_1_fu_322_p3 = ((icmp_ln35_1_reg_645[0:0] == 1'b1) ? tmp_s_reg_618_pp0_iter3_reg : zext_ln35_reg_640);

assign select_ln35_2_fu_334_p3 = ((icmp_ln35_2_reg_662[0:0] == 1'b1) ? tmp_1_reg_624_pp0_iter18_reg : select_ln35_1_reg_651_pp0_iter18_reg);

assign select_ln35_3_fu_221_p3 = ((min_distances_offset_int_reg[0:0] == 1'b1) ? 3'd3 : 3'd0);

assign select_ln35_fu_308_p3 = ((icmp_ln35_reg_630[0:0] == 1'b1) ? trunc_ln35_reg_613_pp0_iter1_reg : 31'd0);

assign select_ln44_1_fu_490_p3 = ((write_flag_fu_364_p10[0:0] == 1'b1) ? zext_ln24_reg_668 : p_read_6_reg_592_pp0_iter19_reg);

assign select_ln44_2_fu_496_p3 = ((write_flag4_fu_427_p10[0:0] == 1'b1) ? zext_ln24_reg_668 : p_read_5_reg_586_pp0_iter19_reg);

assign select_ln44_3_fu_502_p3 = ((write_flag8_fu_469_p10[0:0] == 1'b1) ? zext_ln24_reg_668 : p_read_4_reg_580_pp0_iter19_reg);

assign select_ln44_4_fu_508_p3 = ((write_flag3_fu_448_p10[0:0] == 1'b1) ? zext_ln24_reg_668 : p_read_3_reg_574_pp0_iter19_reg);

assign select_ln44_5_fu_514_p3 = ((write_flag2_fu_406_p10[0:0] == 1'b1) ? zext_ln24_reg_668 : p_read_2_reg_568_pp0_iter19_reg);

assign select_ln44_6_fu_520_p3 = ((write_flag1_fu_385_p10[0:0] == 1'b1) ? zext_ln24_reg_668 : p_read_1_reg_562_pp0_iter19_reg);

assign select_ln44_fu_348_p3 = ((icmp_ln35_2_reg_662[0:0] == 1'b1) ? 2'd2 : zext_ln44_fu_345_p1);

assign tmp_1_fu_285_p7 = ((min_distances_offset_int_reg[0:0] == 1'b1) ? 3'd5 : 3'd2);

assign tmp_fu_229_p7 = ((min_distances_offset_int_reg[0:0] == 1'b1) ? 3'd3 : 3'd0);

assign tmp_s_fu_259_p7 = ((min_distances_offset_int_reg[0:0] == 1'b1) ? 3'd4 : 3'd1);

assign trunc_ln35_fu_247_p1 = tmp_fu_229_p8[30:0];

assign zext_ln24_fu_331_p1 = dist_reg_657;

assign zext_ln35_fu_314_p1 = select_ln35_reg_635;

assign zext_ln44_1_fu_355_p1 = select_ln44_fu_348_p3;

assign zext_ln44_fu_345_p1 = icmp_ln35_1_reg_645_pp0_iter18_reg;

always @ (posedge ap_clk) begin
    select_ln35_3_reg_603[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter1_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter2_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter3_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter4_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter5_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter6_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter7_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter8_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter9_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter10_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter11_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter12_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter13_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter14_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter15_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter16_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter17_reg[2] <= 1'b0;
    select_ln35_3_reg_603_pp0_iter18_reg[2] <= 1'b0;
    zext_ln35_reg_640[31] <= 1'b0;
    zext_ln24_reg_668[31:9] <= 23'b00000000000000000000000;
end

endmodule //update_knn1_update_knn
