// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rasterization2_m,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.267000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=12,HLS_SYN_FF=3685,HLS_SYN_LUT=3225,HLS_VERSION=2018_3}" *)

module rasterization2_m (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_1_V_V,
        Input_1_V_V_ap_vld,
        Input_1_V_V_ap_ack,
        Output_1_V_V,
        Output_1_V_V_ap_vld,
        Output_1_V_V_ap_ack,
        Output_2_V_V,
        Output_2_V_V_ap_vld,
        Output_2_V_V_ap_ack,
        Input_2_V_V,
        Input_2_V_V_ap_vld,
        Input_2_V_V_ap_ack,
        Output_3_V_V,
        Output_3_V_V_ap_vld,
        Output_3_V_V_ap_ack,
        Output_4_V_V,
        Output_4_V_V_ap_vld,
        Output_4_V_V_ap_ack
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] Input_1_V_V;
input   Input_1_V_V_ap_vld;
output   Input_1_V_V_ap_ack;
output  [31:0] Output_1_V_V;
output   Output_1_V_V_ap_vld;
input   Output_1_V_V_ap_ack;
output  [31:0] Output_2_V_V;
output   Output_2_V_V_ap_vld;
input   Output_2_V_V_ap_ack;
input  [31:0] Input_2_V_V;
input   Input_2_V_V_ap_vld;
output   Input_2_V_V_ap_ack;
output  [31:0] Output_3_V_V;
output   Output_3_V_V_ap_vld;
input   Output_3_V_V_ap_ack;
output  [31:0] Output_4_V_V;
output   Output_4_V_V_ap_vld;
input   Output_4_V_V_ap_ack;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Input_1_V_V_ap_ack;
reg Input_2_V_V_ap_ack;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] Output_1_V_V_1_data_reg;
reg    Output_1_V_V_1_vld_reg;
wire    Output_1_V_V_1_vld_in;
reg    Output_1_V_V_1_ack_in;
wire    Output_1_V_V_1_ack_out;
reg   [31:0] Output_2_V_V_1_data_reg;
reg    Output_2_V_V_1_vld_reg;
wire    Output_2_V_V_1_vld_in;
reg    Output_2_V_V_1_ack_in;
wire    Output_2_V_V_1_ack_out;
reg   [31:0] Output_3_V_V_1_data_reg;
reg    Output_3_V_V_1_vld_reg;
wire    Output_3_V_V_1_vld_in;
reg    Output_3_V_V_1_ack_in;
wire    Output_3_V_V_1_ack_out;
reg   [31:0] Output_4_V_V_1_data_reg;
reg    Output_4_V_V_1_vld_reg;
wire    Output_4_V_V_1_vld_in;
reg    Output_4_V_V_1_ack_in;
wire    Output_4_V_V_1_ack_out;
wire    grp_rasterization2_odd_fu_46_ap_start;
wire    grp_rasterization2_odd_fu_46_ap_done;
wire    grp_rasterization2_odd_fu_46_ap_idle;
wire    grp_rasterization2_odd_fu_46_ap_ready;
wire    grp_rasterization2_odd_fu_46_Input_1_V_V_ap_ack;
wire   [31:0] grp_rasterization2_odd_fu_46_Output_1_V_V;
wire    grp_rasterization2_odd_fu_46_Output_1_V_V_ap_vld;
wire    grp_rasterization2_odd_fu_46_Output_1_V_V_ap_ack;
wire   [31:0] grp_rasterization2_odd_fu_46_Output_2_V_V;
wire    grp_rasterization2_odd_fu_46_Output_2_V_V_ap_vld;
wire    grp_rasterization2_odd_fu_46_Output_2_V_V_ap_ack;
wire    grp_rasterization2_even_fu_64_ap_start;
wire    grp_rasterization2_even_fu_64_ap_done;
wire    grp_rasterization2_even_fu_64_ap_idle;
wire    grp_rasterization2_even_fu_64_ap_ready;
wire    grp_rasterization2_even_fu_64_Input_1_V_V_ap_ack;
wire   [31:0] grp_rasterization2_even_fu_64_Output_1_V_V;
wire    grp_rasterization2_even_fu_64_Output_1_V_V_ap_vld;
wire    grp_rasterization2_even_fu_64_Output_1_V_V_ap_ack;
wire   [31:0] grp_rasterization2_even_fu_64_Output_2_V_V;
wire    grp_rasterization2_even_fu_64_Output_2_V_V_ap_vld;
wire    grp_rasterization2_even_fu_64_Output_2_V_V_ap_ack;
reg    grp_rasterization2_odd_fu_46_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_rasterization2_even_fu_64_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    ap_block_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_block_state2_on_subcall_done;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 Output_1_V_V_1_data_reg = 32'd0;
#0 Output_1_V_V_1_vld_reg = 1'b0;
#0 Output_2_V_V_1_data_reg = 32'd0;
#0 Output_2_V_V_1_vld_reg = 1'b0;
#0 Output_3_V_V_1_data_reg = 32'd0;
#0 Output_3_V_V_1_vld_reg = 1'b0;
#0 Output_4_V_V_1_data_reg = 32'd0;
#0 Output_4_V_V_1_vld_reg = 1'b0;
#0 grp_rasterization2_odd_fu_46_ap_start_reg = 1'b0;
#0 grp_rasterization2_even_fu_64_ap_start_reg = 1'b0;
end

rasterization2_odd grp_rasterization2_odd_fu_46(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rasterization2_odd_fu_46_ap_start),
    .ap_done(grp_rasterization2_odd_fu_46_ap_done),
    .ap_idle(grp_rasterization2_odd_fu_46_ap_idle),
    .ap_ready(grp_rasterization2_odd_fu_46_ap_ready),
    .Input_1_V_V(Input_1_V_V),
    .Input_1_V_V_ap_vld(Input_1_V_V_ap_vld),
    .Input_1_V_V_ap_ack(grp_rasterization2_odd_fu_46_Input_1_V_V_ap_ack),
    .Output_1_V_V(grp_rasterization2_odd_fu_46_Output_1_V_V),
    .Output_1_V_V_ap_vld(grp_rasterization2_odd_fu_46_Output_1_V_V_ap_vld),
    .Output_1_V_V_ap_ack(grp_rasterization2_odd_fu_46_Output_1_V_V_ap_ack),
    .Output_2_V_V(grp_rasterization2_odd_fu_46_Output_2_V_V),
    .Output_2_V_V_ap_vld(grp_rasterization2_odd_fu_46_Output_2_V_V_ap_vld),
    .Output_2_V_V_ap_ack(grp_rasterization2_odd_fu_46_Output_2_V_V_ap_ack)
);

rasterization2_even grp_rasterization2_even_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rasterization2_even_fu_64_ap_start),
    .ap_done(grp_rasterization2_even_fu_64_ap_done),
    .ap_idle(grp_rasterization2_even_fu_64_ap_idle),
    .ap_ready(grp_rasterization2_even_fu_64_ap_ready),
    .Input_1_V_V(Input_2_V_V),
    .Input_1_V_V_ap_vld(Input_2_V_V_ap_vld),
    .Input_1_V_V_ap_ack(grp_rasterization2_even_fu_64_Input_1_V_V_ap_ack),
    .Output_1_V_V(grp_rasterization2_even_fu_64_Output_1_V_V),
    .Output_1_V_V_ap_vld(grp_rasterization2_even_fu_64_Output_1_V_V_ap_vld),
    .Output_1_V_V_ap_ack(grp_rasterization2_even_fu_64_Output_1_V_V_ap_ack),
    .Output_2_V_V(grp_rasterization2_even_fu_64_Output_2_V_V),
    .Output_2_V_V_ap_vld(grp_rasterization2_even_fu_64_Output_2_V_V_ap_vld),
    .Output_2_V_V_ap_ack(grp_rasterization2_even_fu_64_Output_2_V_V_ap_ack)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rasterization2_even_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_rasterization2_even_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_rasterization2_even_fu_64_ap_ready == 1'b1)) begin
            grp_rasterization2_even_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rasterization2_odd_fu_46_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_rasterization2_odd_fu_46_ap_start_reg <= 1'b1;
        end else if ((grp_rasterization2_odd_fu_46_ap_ready == 1'b1)) begin
            grp_rasterization2_odd_fu_46_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == Output_1_V_V_1_vld_reg) & (1'b1 == Output_1_V_V_1_vld_in))) begin
        Output_1_V_V_1_vld_reg <= 1'b1;
    end else if (((1'b0 == Output_1_V_V_1_vld_in) & (1'b1 == Output_1_V_V_1_ack_out) & (1'b1 == Output_1_V_V_1_vld_reg))) begin
        Output_1_V_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == Output_2_V_V_1_vld_reg) & (1'b1 == Output_2_V_V_1_vld_in))) begin
        Output_2_V_V_1_vld_reg <= 1'b1;
    end else if (((1'b0 == Output_2_V_V_1_vld_in) & (1'b1 == Output_2_V_V_1_ack_out) & (1'b1 == Output_2_V_V_1_vld_reg))) begin
        Output_2_V_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == Output_3_V_V_1_vld_reg) & (1'b1 == Output_3_V_V_1_vld_in))) begin
        Output_3_V_V_1_vld_reg <= 1'b1;
    end else if (((1'b0 == Output_3_V_V_1_vld_in) & (1'b1 == Output_3_V_V_1_ack_out) & (1'b1 == Output_3_V_V_1_vld_reg))) begin
        Output_3_V_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == Output_4_V_V_1_vld_reg) & (1'b1 == Output_4_V_V_1_vld_in))) begin
        Output_4_V_V_1_vld_reg <= 1'b1;
    end else if (((1'b0 == Output_4_V_V_1_vld_in) & (1'b1 == Output_4_V_V_1_ack_out) & (1'b1 == Output_4_V_V_1_vld_reg))) begin
        Output_4_V_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == Output_1_V_V_1_vld_reg) & (1'b1 == Output_1_V_V_1_vld_in)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == Output_1_V_V_1_ack_out) & (1'b1 == Output_1_V_V_1_vld_in) & (1'b1 == Output_1_V_V_1_vld_reg)))) begin
        Output_1_V_V_1_data_reg <= grp_rasterization2_odd_fu_46_Output_1_V_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == Output_2_V_V_1_vld_reg) & (1'b1 == Output_2_V_V_1_vld_in)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == Output_2_V_V_1_ack_out) & (1'b1 == Output_2_V_V_1_vld_in) & (1'b1 == Output_2_V_V_1_vld_reg)))) begin
        Output_2_V_V_1_data_reg <= grp_rasterization2_odd_fu_46_Output_2_V_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == Output_3_V_V_1_vld_reg) & (1'b1 == Output_3_V_V_1_vld_in)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == Output_3_V_V_1_ack_out) & (1'b1 == Output_3_V_V_1_vld_in) & (1'b1 == Output_3_V_V_1_vld_reg)))) begin
        Output_3_V_V_1_data_reg <= grp_rasterization2_even_fu_64_Output_1_V_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == Output_4_V_V_1_vld_reg) & (1'b1 == Output_4_V_V_1_vld_in)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == Output_4_V_V_1_ack_out) & (1'b1 == Output_4_V_V_1_vld_in) & (1'b1 == Output_4_V_V_1_vld_reg)))) begin
        Output_4_V_V_1_data_reg <= grp_rasterization2_even_fu_64_Output_2_V_V;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Input_1_V_V_ap_ack = grp_rasterization2_odd_fu_46_Input_1_V_V_ap_ack;
    end else begin
        Input_1_V_V_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Input_2_V_V_ap_ack = grp_rasterization2_even_fu_64_Input_1_V_V_ap_ack;
    end else begin
        Input_2_V_V_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == Output_1_V_V_1_vld_reg) | ((1'b1 == Output_1_V_V_1_ack_out) & (1'b1 == Output_1_V_V_1_vld_reg)))) begin
        Output_1_V_V_1_ack_in = 1'b1;
    end else begin
        Output_1_V_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == Output_2_V_V_1_vld_reg) | ((1'b1 == Output_2_V_V_1_ack_out) & (1'b1 == Output_2_V_V_1_vld_reg)))) begin
        Output_2_V_V_1_ack_in = 1'b1;
    end else begin
        Output_2_V_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == Output_3_V_V_1_vld_reg) | ((1'b1 == Output_3_V_V_1_ack_out) & (1'b1 == Output_3_V_V_1_vld_reg)))) begin
        Output_3_V_V_1_ack_in = 1'b1;
    end else begin
        Output_3_V_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == Output_4_V_V_1_vld_reg) | ((1'b1 == Output_4_V_V_1_ack_out) & (1'b1 == Output_4_V_V_1_vld_reg)))) begin
        Output_4_V_V_1_ack_in = 1'b1;
    end else begin
        Output_4_V_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == Output_3_V_V_1_ack_in) | (1'b0 == Output_2_V_V_1_ack_in) | (1'b0 == Output_1_V_V_1_ack_in) | (1'b0 == Output_4_V_V_1_ack_in)) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == Output_3_V_V_1_ack_in) | (1'b0 == Output_2_V_V_1_ack_in) | (1'b0 == Output_1_V_V_1_ack_in) | (1'b0 == Output_4_V_V_1_ack_in)) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((1'b0 == Output_3_V_V_1_ack_in) | (1'b0 == Output_2_V_V_1_ack_in) | (1'b0 == Output_1_V_V_1_ack_in) | (1'b0 == Output_4_V_V_1_ack_in)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Output_1_V_V = Output_1_V_V_1_data_reg;

assign Output_1_V_V_1_ack_out = Output_1_V_V_ap_ack;

assign Output_1_V_V_1_vld_in = grp_rasterization2_odd_fu_46_Output_1_V_V_ap_vld;

assign Output_1_V_V_ap_vld = Output_1_V_V_1_vld_reg;

assign Output_2_V_V = Output_2_V_V_1_data_reg;

assign Output_2_V_V_1_ack_out = Output_2_V_V_ap_ack;

assign Output_2_V_V_1_vld_in = grp_rasterization2_odd_fu_46_Output_2_V_V_ap_vld;

assign Output_2_V_V_ap_vld = Output_2_V_V_1_vld_reg;

assign Output_3_V_V = Output_3_V_V_1_data_reg;

assign Output_3_V_V_1_ack_out = Output_3_V_V_ap_ack;

assign Output_3_V_V_1_vld_in = grp_rasterization2_even_fu_64_Output_1_V_V_ap_vld;

assign Output_3_V_V_ap_vld = Output_3_V_V_1_vld_reg;

assign Output_4_V_V = Output_4_V_V_1_data_reg;

assign Output_4_V_V_1_ack_out = Output_4_V_V_ap_ack;

assign Output_4_V_V_1_vld_in = grp_rasterization2_even_fu_64_Output_2_V_V_ap_vld;

assign Output_4_V_V_ap_vld = Output_4_V_V_1_vld_reg;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_rasterization2_even_fu_64_ap_done == 1'b0) | (grp_rasterization2_odd_fu_46_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((1'b0 == Output_3_V_V_1_ack_in) | (1'b0 == Output_2_V_V_1_ack_in) | (1'b0 == Output_1_V_V_1_ack_in) | (1'b0 == Output_4_V_V_1_ack_in));
end

assign grp_rasterization2_even_fu_64_Output_1_V_V_ap_ack = (ap_CS_fsm_state2 & Output_3_V_V_1_ack_in);

assign grp_rasterization2_even_fu_64_Output_2_V_V_ap_ack = (ap_CS_fsm_state2 & Output_4_V_V_1_ack_in);

assign grp_rasterization2_even_fu_64_ap_start = grp_rasterization2_even_fu_64_ap_start_reg;

assign grp_rasterization2_odd_fu_46_Output_1_V_V_ap_ack = (ap_CS_fsm_state2 & Output_1_V_V_1_ack_in);

assign grp_rasterization2_odd_fu_46_Output_2_V_V_ap_ack = (ap_CS_fsm_state2 & Output_2_V_V_1_ack_in);

assign grp_rasterization2_odd_fu_46_ap_start = grp_rasterization2_odd_fu_46_ap_start_reg;

endmodule //rasterization2_m
