# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /scratch/safe/SymbiFlow/symbiflow-arch-defs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /scratch/safe/SymbiFlow/symbiflow-arch-defs/build

# Utility rule file for file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml.

# Include the progress variables for this target.
include xc7/archs/artix7/devices/CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml.dir/progress.make

xc7/archs/artix7/devices/CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml: xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.real.xml


xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.real.xml: xc7/archs/artix7/devices/xc7a50t-basys3-roi-virt/channels.db
xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.real.xml: xc7/archs/artix7/devices/xc7a50t-basys3-roi-virt/synth_tiles.json
xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.real.xml: xc7/archs/artix7/devices/xc7a50t-basys3-roi-virt/arch.unique_pack.xml
xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.real.xml: xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.virt.xml
xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.real.xml: ../xc7/utils/prjxray_routing_import.py
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/scratch/safe/SymbiFlow/symbiflow-arch-defs/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Generating rr_graph_xc7a50t-basys3_test.rr_graph.real.xml"
	cd /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices && /usr/bin/cmake -E env PYTHONPATH=/scratch/safe/SymbiFlow/symbiflow-arch-defs/third_party/prjxray:/scratch/safe/SymbiFlow/symbiflow-arch-defs/utils:/scratch/safe/SymbiFlow/symbiflow-arch-defs/build/utils /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/env/conda/bin/python3 /scratch/safe/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_routing_import.py --db_root /scratch/safe/SymbiFlow/symbiflow-arch-defs/third_party/prjxray-db/artix7 --read_rr_graph /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.virt.xml --write_rr_graph /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.real.xml --synth_tiles /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices/xc7a50t-basys3-roi-virt/synth_tiles.json --connection_database /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices/xc7a50t-basys3-roi-virt/channels.db --prflow nothing_to_see_here

xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.virt.xml: ../common/wire.eblif
xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.virt.xml: xc7/archs/artix7/devices/xc7a50t-basys3-roi-virt/arch.unique_pack.xml
xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.virt.xml: ../utils/quiet_cmd.sh
xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.virt.xml: env/conda/bin/vpr
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/scratch/safe/SymbiFlow/symbiflow-arch-defs/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Generating rr_graph_xc7a50t-basys3_test.rr_graph.virt.xml, rr_graph_xc7a50t-basys3_test.virt.out"
	cd /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices && /scratch/safe/SymbiFlow/symbiflow-arch-defs/utils/quiet_cmd.sh /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/env/conda/bin/vpr /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices/xc7a50t-basys3-roi-virt/arch.unique_pack.xml --device xc7a50t-basys3-test /scratch/safe/SymbiFlow/symbiflow-arch-defs/common/wire.eblif --route_chan_width 6 --echo_file on --min_route_chan_width_hint 1 --write_rr_graph /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.virt.xml --outfile_prefix xc7a50t-basys3_test --pack --place
	cd /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices && /usr/bin/cmake -E copy vpr_stdout.log rr_graph_xc7a50t-basys3_test.virt.out

xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.virt.out: xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.virt.xml
	@$(CMAKE_COMMAND) -E touch_nocreate xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.virt.out

file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml: xc7/archs/artix7/devices/CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml
file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml: xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.real.xml
file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml: xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.rr_graph.virt.xml
file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml: xc7/archs/artix7/devices/rr_graph_xc7a50t-basys3_test.virt.out
file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml: xc7/archs/artix7/devices/CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml.dir/build.make

.PHONY : file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml

# Rule to build all files generated by this target.
xc7/archs/artix7/devices/CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml.dir/build: file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml

.PHONY : xc7/archs/artix7/devices/CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml.dir/build

xc7/archs/artix7/devices/CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml.dir/clean:
	cd /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices && $(CMAKE_COMMAND) -P CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml.dir/cmake_clean.cmake
.PHONY : xc7/archs/artix7/devices/CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml.dir/clean

xc7/archs/artix7/devices/CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml.dir/depend:
	cd /scratch/safe/SymbiFlow/symbiflow-arch-defs/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /scratch/safe/SymbiFlow/symbiflow-arch-defs /scratch/safe/SymbiFlow/symbiflow-arch-defs/xc7/archs/artix7/devices /scratch/safe/SymbiFlow/symbiflow-arch-defs/build /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices /scratch/safe/SymbiFlow/symbiflow-arch-defs/build/xc7/archs/artix7/devices/CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : xc7/archs/artix7/devices/CMakeFiles/file_xc7_archs_artix7_devices_rr_graph_xc7a50t-basys3_test.rr_graph.real.xml.dir/depend

