// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module projection (
        ap_ready,
        triangle_2d_x0_V_wri,
        triangle_2d_y0_V_wri,
        triangle_3d_z0_V,
        triangle_2d_x1_V_wri,
        triangle_2d_y1_V_wri,
        triangle_3d_z1_V,
        triangle_2d_x2_V_wri,
        triangle_2d_y2_V_wri,
        triangle_3d_z2_V,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6
);


output   ap_ready;
input  [7:0] triangle_2d_x0_V_wri;
input  [7:0] triangle_2d_y0_V_wri;
input  [7:0] triangle_3d_z0_V;
input  [7:0] triangle_2d_x1_V_wri;
input  [7:0] triangle_2d_y1_V_wri;
input  [7:0] triangle_3d_z1_V;
input  [7:0] triangle_2d_x2_V_wri;
input  [7:0] triangle_2d_y2_V_wri;
input  [7:0] triangle_3d_z2_V;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;

wire   [7:0] mul_ln1371_fu_88_p0;
wire   [17:0] mul_ln1371_fu_88_p2;
wire   [7:0] mul_ln1371_1_fu_108_p0;
wire   [17:0] mul_ln1371_1_fu_108_p2;
wire   [7:0] mul_ln1371_2_fu_128_p0;
wire   [17:0] mul_ln1371_2_fu_128_p2;
wire   [7:0] udiv_ln_fu_94_p4;
wire   [7:0] udiv_ln1371_2_fu_134_p4;
wire   [7:0] add_ln214_fu_144_p2;
wire   [7:0] udiv_ln1371_1_fu_114_p4;
wire   [7:0] add_ln214_1_fu_150_p2;
wire   [17:0] mul_ln1371_1_fu_108_p00;
wire   [17:0] mul_ln1371_2_fu_128_p00;
wire   [17:0] mul_ln1371_fu_88_p00;

assign add_ln214_1_fu_150_p2 = (add_ln214_fu_144_p2 + udiv_ln1371_1_fu_114_p4);

assign add_ln214_fu_144_p2 = (udiv_ln_fu_94_p4 + udiv_ln1371_2_fu_134_p4);

assign ap_ready = 1'b1;

assign ap_return_0 = triangle_2d_x0_V_wri;

assign ap_return_1 = triangle_2d_y0_V_wri;

assign ap_return_2 = triangle_2d_x1_V_wri;

assign ap_return_3 = triangle_2d_y1_V_wri;

assign ap_return_4 = triangle_2d_x2_V_wri;

assign ap_return_5 = triangle_2d_y2_V_wri;

assign ap_return_6 = add_ln214_1_fu_150_p2;

assign mul_ln1371_1_fu_108_p0 = mul_ln1371_1_fu_108_p00;

assign mul_ln1371_1_fu_108_p00 = triangle_3d_z1_V;

assign mul_ln1371_1_fu_108_p2 = (mul_ln1371_1_fu_108_p0 * $signed('h156));

assign mul_ln1371_2_fu_128_p0 = mul_ln1371_2_fu_128_p00;

assign mul_ln1371_2_fu_128_p00 = triangle_3d_z2_V;

assign mul_ln1371_2_fu_128_p2 = (mul_ln1371_2_fu_128_p0 * $signed('h156));

assign mul_ln1371_fu_88_p0 = mul_ln1371_fu_88_p00;

assign mul_ln1371_fu_88_p00 = triangle_3d_z0_V;

assign mul_ln1371_fu_88_p2 = (mul_ln1371_fu_88_p0 * $signed('h156));

assign udiv_ln1371_1_fu_114_p4 = {{mul_ln1371_1_fu_108_p2[17:10]}};

assign udiv_ln1371_2_fu_134_p4 = {{mul_ln1371_2_fu_128_p2[17:10]}};

assign udiv_ln_fu_94_p4 = {{mul_ln1371_fu_88_p2[17:10]}};

endmodule //projection
