<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" projectType="C/C++" name="ydma" top="ydma">
    <files>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/gradient_weight_x2.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/outer_product2.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/flow_calc_1.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/gradient_weight_x1.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/gradient_weight_y_3.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/gradient_weight_x3.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/tensor_weight_x2.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/tensor_weight_y2.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/output_fun.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/tensor_weight_x1.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/tensor_weight_y1.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/gradient_weight_y_2.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/outer_product1.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/flow_calc_2.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/gradient_xyz_calc.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/operators/gradient_weight_y_1.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host/typedefs.h" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
        <file name="/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host/top.cpp" sc="0" tb="false" cflags="-g -I/opt/Xilinx/Vivado/2021.1/include -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk -I/home/ylxiao/ws_211/prflow_riscv/input_src/optical_flow_bk/host" csimflags="" blackbox="false"/>
    </files>
    <solutions>
        <solution name="solution" status=""/>
    </solutions>
</AutoPilot:project>

