YOSYS_XILINX = /scratch/safe/SymbiFlow/symbiflow-arch-defs.grid/build/env/conda/share/yosys/xilinx

install:
	cp  $(YOSYS_XILINX)/xc7_xcu_brams.txt $(YOSYS_XILINX)/xc7_xcu_brams.txt.`date +"%m_%d_%Y_%H_%M"`
	cp brams.txt $(YOSYS_XILINX)/xc7_xcu_brams.txt



